routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/create', function (){
	return view('shares/create');
});
Route::resource('shares','ShareController');

app/Share.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Share extends Model
{
	public $table = 'shares';
    public $fillable = [
    	'name',
    	'price',
    ];
    public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ShareController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validate\Rule;
use Illuminate\Database\Eloquent\Model;
use App\Share;
use App\Model\statusModel;
use Illuminate\Sopport\Facades\Validator;

use Auth;


class ShareController extends Controller
{
    
    public function index()
    {
    	$shares = Share::all();

     //    if (count($shares) > 0) {
     //        $message = "data is available";
     //        $result = array("result" =>1 ,
     //        "message"=> $message,
     //        "data" => $shares );
     //    }else{
     //        $message = "Data is not found";
     //        $result = array(
     //            "result" => 0,
     //            "message" => $message,
     //             );
     //    }
    	// return json_encode($result);
        return view('shares.index',compact('shares'));
    }

    public function create()
    {
    	return view('shares.create');
    }

    public function store(Request $request)
    {

    // $request->validate([
    // 	'name'=>'required',
    // 	'price'=>'required|integer'
    // ]);
    
    $share = new Share([
    	'name' => $request->get('name'),
    	'price' => $request->get('price')
    ]);

    $share->save();
    // 
    return response(['succes'=>true]);
    }

    public function show($id)
    {
    	# code...
    }

    public function edit($id)
    {
    	$share = Share::find($id);
    	return view('shares.edit', compact('share'));
    }

    public function update(Request $request, $id)
    {
    	// $request->validate([
    	// 	'name'=>'required',
    	// 	'price'=>'required|integer'
    	// ]);

    	$share = Share::find($id);
    	$share->name = $request->get('name');
    	$share->price = $request->get('price');
    	$share->save();
    	// return redirect('/shares')->with('succes', 'Data has been update');
        return response(['succes'=>true]);
    }

    public function destroy($id)
    {
    	$share = Share::find($id);
    	$share->delete();

    	return redirect('/shares')->with('success', 'Data has been deleted ');
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Crud</title>
	<link href="{{ asset('css/app.css') }}"
	rel="stylesheet" type="text/css" />
</head>
<body>
	<div class="container">
		@yield('content')
	</div>
	<script
	  src="https://code.jquery.com/jquery-3.3.1.min.js"
  	  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  	  crossorigin="anonymous"></script>
  	  @stack('script')
	<script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/shares/create.blade.php
@extends('layout')
@section('content')
<style>
	.uper{
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">
		Add share
	</div>
	<div class="card-body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div><br/>
		@endif
		<form id="form" method="post" action="{{ route('shares.store') }}">
			<div class="form-group">
				@csrf
				<label for="name">Share Name:</label>
				<input type="text" class="form-control" name="name"/>
			</div>

				<div class="form-group">
				<label for="price">Share Price:</label>
				<input type="text" class="form-control" name="price"/>
			</div>
			<button type="submit" class="btn btn-primary">Add</button>
		</form>
	</div>
</div>
@endsection

@push('script')
<script>
	$('#form').submit(function(event){
		event.preventDefault()
		$.ajax({
			url: "{{ route('shares.store') }}",
			method: "POST",
			data: $(this).serialize()
		})
		.done(function(data){
			alert('sukses')
		});
	})
</script>
@endpush

resources/views/shares/edit.blade.php
@extends('layout')
@section('content')
<style>
	.uper{
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">
		Edit Share
	</div>
	<div class="card-body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
		<br/>
		@endif
		<form id="form" method="post" action="{{ route('shares.update',$share->id )}}">
			@method('PATCH')
			@csrf
			<div class="form-group">
				<label for="name">Name :</label>
				<input type="text" class="form-control" name="name" value={{ $share->name}}>
			</div>
			<div class="form-group">
				<label for="name">Price :</label>
				<input type="text" class="form-control" name="price" value={{ $share->price}}>
			</div>
			<button type="submit" class="btn btn-primary">Update</button>
		</form>
	</div>
</div>
@endsection
@push('script')
<script>
	$('#form').submit(function(event){
		event.preventDefault()
		$.ajax({
			url: "{{ route('shares.update',$share->id) }}",
			method: "PATCH",
			data: $(this).serialize()
		})
		.done(function( data ){
			alert('sukses')
		});
	})
</script>
@endpush

resources/views/shares/index.blade.php
@extends('layout')

@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="uper">
	@if(session()->get('succes'))
	<div class="alert alert-success">
		{{ session()->get('success') }}
	</div><br/>
	@endif

	<h1>CRUD LARAVEL</h1>
	<table class="table table-striped">
		<thead>
			<tr>
				<td>ID</td>
				<td>Name</td>
				<td>Price</td>
				<td colspan="2">Action</td>
			</tr>
		</thead>
		<tbody>
			@foreach($shares as $share)
			<tr>
				<td>{{$share->id}}</td>
				<td>{{$share->name}}</td>
				<td>{{$share->price}}</td>
				<td><a href="{{ route('shares.edit',$share->id)}}" class="btn btn-primary">Edit</a></td>
				<td>
				<form id="form" action="{{ route('shares.destroy',$share->id)}}" method="post">
					@csrf
					@method('DELETE')
					<button class="btn btn-danger" type="submit">Delete</button>
				</form>
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
	<a href="{{ url('/create') }}"><button type="submit" class="btn btn-primary">Create New Data</button></a>
</div>
@endsection

@push('script')
<script>
	$('#form').submit(function(event){
		event.preventDefault()
		$.ajax({
			url: "{{ route('shares.destroy',$share->id)}}",
			method: "DELETE",
			data: $(this).serialize()
		})
		.done(function(data){
			alert('sukses')
		});
	})
</script>
@endpush